mychat/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^post_list/$',views.PostListApiView.as_view(),name="post_list_api"),
    url(r'^userinfo_detail/(?P<pk>\w+)/$',views.UserInfoDetailApiView.as_view(),name="userinfo_detail_api"),
    url(r'post_detail/(?P<pk>\w+)/$',views.PostDetailApiView.as_view(),name="post_detail_api"),
    url(r'userinfo_list/$',views.UserInfoListApiView.as_view(),name="userinfo_list_api"),
    url(r'user_list/$',views.UserListApiView.as_view(),name="user_list_api"),
    url(r'user_detail/(?P<pk>\w+)/$',views.UserDetailView.as_view(),name="user_detail_api")
]
from rest_framework.authtoken import views
urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token)
]

mychat/app_one/urls.py
from django.conf.urls import url
from app_one import views

app_name='app_one'
urlpatterns=[
    # url(r'^create_post/$',views.CreatePost.as_view(),name="post_create"),
    url(r'^home/$',views.HomeView.as_view(),name="home"),
    url(r'^logout/$',views.user_logout,name="logout"),
    url(r'^login/$',views.user_login,name="login"),
    url(r'^signup/$',views.SignUpView.as_view(),name="signup"),
    url(r'^$',views.IndexView.as_view(),name="index"),
    url(r'^profile/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(),name="profile"),
    url(r'^follow/(?P<user_i_want_to_follow_id>\d+)/$',views.follow_view,name="follow"),
    url(r'^add_comment/(?P<pk>\d+)/(?P<from>\w+)/$',views.comment_view,name="comment"),
    url(r'^like/(?P<pk>\d+)/(?P<from>\w+)/$',views.like_view,name="like"),
    # url(r'^chat_board/$',views.ChatBoardView.as_view(),name="chat_board")
]

mychat/mychat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
# from app_one import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/',admin.site.urls),
    url(r'^api/',include('api.urls')),
    url(r'^',include('app_one.urls')),
]
from django.conf import settings
from django.views.static import serve
if settings.DEBUG:
    urlpatterns+=[url(r'^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT})]

mychat/app_one/models.py
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
# Create your views here.

from django.contrib import auth
from django.urls import reverse

class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    # friend=models.ManyToManyField(User,related_name='friends',blank=True)
    following=models.ManyToManyField('UserInfo',related_name='followers',blank=True)
    # likes=models.ManyToManyField('Post',related_name='liked_by',blank=True)
    def __str__(self):
        return "@"+self.user.username

    # def get_absolute_url(self):
    #
    #     return reverse('app_one:profile',kwargs={'pk':self.user.id})

# class FriendShip(models.Model):
#     person1=models.ForeignKey(UserInfo,related_name='friendships1',on_delete=models.CASCADE)
#     person2=models.ForeignKey(UserInfo,related_name='friendships2',on_delete=models.CASCADE)
#     date=models.DateTimeField(default=timezone.now)
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        from push_notifications.models import APNSDevice, GCMDevice
        reg_id="cBctKUFReTM:APA91bHgJ1Mwi-zbMhCzUtdfnxX-5KTe1enGWDvHZZVZwcrCSH7GgEpnSMiiwj-FWCmfXil84NaGRZ_f5RLhk6X97ufMy1iRsuKZWsB7HXZz609MAb7Z4Yt_F84tx_7X96lIDDu0b9Vw"
        fcm_device = GCMDevice.objects.create(registration_id=reg_id, cloud_message_type="FCM")

        # device = GCMDevice.objects.get(registration_id=gcm_reg_id)
        device=fcm_device
        # The first argument will be sent as "message" to the intent extras Bundle
        # Retrieve it with intent.getExtras().getString("message")
        device.send_message("You've got mail"+instance.username)

class Post(models.Model):
    posted_by=models.ForeignKey(UserInfo,related_name='posts',on_delete=models.CASCADE,null=True,blank=True)
    image=models.ImageField(upload_to="image/%Y/%m/%D/",blank=True,null=True)
    title=models.CharField(max_length=255)
    message=models.TextField()
    likes=models.ManyToManyField(UserInfo,related_name='post_liked',blank=True)
    date_of_posting=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    message=models.TextField()
    commented_by=models.ForeignKey(UserInfo,related_name='user_comments',on_delete=models.CASCADE)
    date_of_commenting=models.DateTimeField(default=timezone.now)
    # Likes=models.IntegerField()

    def __str__(self):
        return self.message

# class ChatRoom(models.Model):
#     chat_room_name=models.CharField(max_length=256,blank=True)
#     persons=models.ManyToManyField(UserInfo,related_name='chat_rooms',blank=True)
# class Message(models.Model):
#     chatRoom=models.ForeignKey(ChatRoom,related_name='messages',on_delete=models.CASCADE)
#     message=models.TextField()
#     sender=models.ForeignKey(UserInfo,related_name='messages_as_sender',on_delete=models.CASCADE)
#     recipient=models.ForeignKey(UserInfo,related_name='messages_as_recipient',on_delete=models.CASCADE)
#     date_of_messaging=models.DateTimeField(timezone.now)

mychat/app_one/forms.py
from django import forms
from app_one.models import Post,Comment
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta():
        model=Post
        fields=['message','title']


class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password']

mychat/app_one/views.py
#views
from django.views.generic import (TemplateView,CreateView,ListView,DetailView)
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from app_one.models import  Post,Comment,UserInfo
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from app_one.forms import UserForm,PostForm
from django.contrib.auth.models import User
from .models import UserInfo,Post,Comment

class HomeView(ListView):
    model=Post
    template_name='app_one/home.html'
    context_object_name='post_list'
    def get_queryset(self):
        userinfo=UserInfo.objects.get(user=self.request.user)
        my_query_set=Post.objects.filter(posted_by=userinfo).order_by('-date_of_posting')[:1]
        for people in userinfo.following.all() :
            sub_query=Post.objects.filter(posted_by=people).order_by('-date_of_posting')
            print(sub_query)
            my_query_set=my_query_set | sub_query
        return my_query_set
# class CreatePost(CreateView):
#     # form_class=PostForm
#     model=Post
#     template_name='app_one/post_create.html'

class IndexView(TemplateView):
    template_name='app_one/index.html'

class ProfileDetailView(DetailView):
    model=UserInfo
    template_name='app_one/profile.html'
    context_object_name='userinfo'
    def post(self,request,*args,**kwargs):
        username_to_be_find=request.POST.get('username_to_be_find',default="n")
        message=request.POST.get('message',default="m")
        title=request.POST.get('title')

        if username_to_be_find!="n":
            user_to_be_find=User.objects.get(username=username_to_be_find)
            userinfo_to_be_find=UserInfo.objects.get(user=user_to_be_find)
            return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':user_to_be_find.id}))
        else:
            userinfo=UserInfo.objects.get(user=request.user)
            post=Post(message=message,title=title,posted_by=userinfo)
            post.save()
            return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':request.user.id}))



class SignUpView(CreateView):
    model=User
    form_class=UserForm
    template_name='app_one/signup.html'
    def form_valid(self, form):
            user_form=form

            user=user_form.save()
            user.set_password(user.password)
            user.save()
            userInfo=UserInfo(user=user,id=user.id)
            userInfo.save()

            return HttpResponseRedirect(reverse('app_one:index'))

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user= authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':request.user.id}))
            else:
                return HttpResponse("Account Not Active")
        else:
            return HttpResponse("Invalid Details")
    else:
        return render(request,'app_one/login.html',{})
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_one:index'))

def comment_view(request,*args,**kwargs):
    message=request.POST.get('comment')
    userinfo=UserInfo.objects.get(user=request.user)
    post=Post.objects.get(id=kwargs['pk'])
    comment=Comment(message=message,commented_by=userinfo,post=post)
    comment.save()
    if kwargs['from']=='profile':
        return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':post.posted_by.id}))
    else:
        return HttpResponseRedirect(reverse('app_one:home'))

def like_view(request,*args,**kwargs):
    post=Post.objects.get(id=kwargs['pk'])
    # profile_username=kwargs['profile_username']
    # profile_user=User.objects.get(username=profile_username)
    userinfo=UserInfo.objects.get(user=request.user)
    post.likes.add(userinfo)
    post.save()
    # return HttpResponse(profile_user)
    if kwargs['from']=='profile':
        return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':post.posted_by.id}))
    else:
        return HttpResponseRedirect(reverse('app_one:home'))
def follow_view(request,*args,**kwargs):
    user_i_want_to_follow=UserInfo.objects.get(id=kwargs['user_i_want_to_follow_id'])
    me=UserInfo.objects.get(user=request.user)
    me.following.add(user_i_want_to_follow)
    me.save()
    # return HttpResponse(me)
    return HttpResponseRedirect(reverse('app_one:profile',kwargs={'pk':user_i_want_to_follow.id}))

# class ChatBoardView(ListView):
#     model=ChatRoom
#     context_object_name=chat_room_list
#     template_name='chat_board.html'
#     def get_queryset(self):
#         userinfo=UserInfo.objects.get(user=self.request.user)
#         return userinfo.following.all()

mychat/templates/app_one/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Here you can share your views,articles with your friends and followers">
    <meta name="keywords" content="Blog,social media,articles">
    <title>WeWrite - Best Text Blogging Platform</title>
    <meta name="author" content="Yash Gupta-DTU">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'CSS/my_css.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <a href="{% url 'app_one:index' %}" class="navbar-brand">WeWrite</a>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'app_one:logout' %}" class="nav-link">Logout</a></li>
            <li class="nav-item"><a href="{% url 'app_one:home' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{% url 'app_one:profile' pk=user.id %}" class="nav-link">@{{user.username}}</a></li>
        {% else %}
            <li class="nav-item"><a href="{% url 'app_one:login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'app_one:signup' %}" class="nav-link">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block body_block %}


    {% endblock %}
  </body>
</html>

mychat/templates/app_one/home.html
{% extends "app_one/base.html" %}
{% load staticfiles %}
  {% block body_block %}
  {% if post_list %}
     {% for post in post_list %}
     <div class="container">
       <div class="card">
         <div class="card-header">
           <h3 class="Mytitle">{{post.title}}</h3>
           <h6>@{{post.posted_by.user.username}}, {{post.date_of_posting}}</h6>

         </div>

         <p class="Mymessage px-4">{{ post.message }}</p>
         <p class="px-2"><a href="{% url 'app_one:like' pk=post.id from='home' %}">Likes</a>:{{post.likes.all|length}}  <a href="#">comments</a>:{{post.comments.all|length}}
         </p>

       </div>
       <form action="{% url 'app_one:comment' pk=post.id from='home' %}" method="post">
         {% csrf_token %}
         <div class="form-row">
           <div class="form-group col-lg-10">
               <input type="text" name="comment" class="form-control" placeholder="Add a comment...">
           </div>
           <div class="col-lg-2">
             <input type="submit" class="btn btn-primary btn-block " value="Comment">
           </div>
         </div>

       </form>
       <div class="card">
       {% for comment in post.comments.all %}
           <h6 class="px-2">{{comment.commented_by}}, {{comment.date_of_commenting}}</h6>
           <p class="Mymessage px-4">{{comment.message}}</p>

       {% endfor %}
       </div>
     </div>

     <br><br>
     {% endfor %}
   {% else %}
     <h3>No post</h3>
   {% endif %}
  <!-- <div class="container">
    {% for post in post_list %}
      {{ post.message }}
      {{ post.posted_by.user.username}}
    {% endfor %}
  </div> -->
  {% endblock %}

mychat/templates/app_one/index.html
{% extends "app_one/base.html" %}
{% load staticfiles %}
  {% block body_block %}

  <div class="container">
    <div class="jumbotron">
      <div class="row">
        <div class="col-sm-4">
          <img src="{% static 'images/mychat_logo.png' %}" alt="">
        </div>
        <div class="col-sm-8">
          <h1 class="display-4">WeWrite</h1>
          <p class="lead">A platform to share your views,Articles with your friends and followers</p>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

mychat/templates/app_one/login.html
{% extends "app_one/base.html" %}
  {% block body_block %}

<br>
    <div class="card container w-25">
      <div class="card-body">
        <h2 class="card-title text-center"><strong>Login Here</strong></h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-group row ">
            <label for="username_id" class="col-2-lg" >Username:</label>
            <input type="text" id="username_id" class="form-control col-8-lg" name="username" placeholder="username">
          </div>
          <div class="form-group row ">
            <label for="password_id" >Password:</label>
            <input type="password" class="form-control col-8-lg " name="password" id="password_id" placeholder="password">
          </div>
          <input type="submit" class="btn btn-primary" value="Login">
        </form>
      </div>
    </div>



  {% endblock %}

mychat/templates/app_one/profile.html
{% extends "app_one/base.html" %}
{% load staticfiles %}
  {% block body_block %}
  <!-- <div class="alert alert-primary " id="my_alert" role="alert" >
  Sorry!!We are still working on it
</div> -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <form class="form-inline my-2 my-lg-0 mx-auto" method="POST" >
      {% csrf_token %}
      <div class="form-group">
        <input type="search"  class="form-control mr-sm-2 "id=""   name="username_to_be_find" placeholder="Search by Username">
      </div>
      <input type="submit" class="btn btn-outline-success my-2 mr-sm-0" value="Search">
    </form>
  </nav>
  <div class="container">
  <div class="card ">
    <div class="row">
      <img src="{% static 'images/user_pic.png' %}" class="col-sm-2 my-2 mx-4" alt="">
      <div class="col-sm-8 my-4">
        <div class="row">
          <h3 class="col-sm-4">{{ userinfo.user.first_name}} {{userinfo.user.last_name}}</h3>
        </div>
        <h5 class="username">@{{userinfo.user.username}}</h5>
        <div class="row">
          <p class="col-sm-2"><strong>Followers</strong></p>
          <p class="col-sm-2"><strong>{{ userinfo.followers.all|length}}</strong></p>
          <p class="col-sm-2"><strong>Following</strong></p>
          <p class="col-sm-2"><strong>{{ userinfo.following.all|length}}</strong></p>

        </div>
        <div class="row">
          <p class="col-sm-2"><strong>Posts</strong></p>
          <p class="col-sm-2"><strong>{{ userinfo.posts.all|length}}</strong></p>

        </div>
        <br>
          {%ifequal userinfo.user user %}
          <button type="button" name="edit_profile" id="edit_profile" class="btn btn-warning" >Edit Profile</button>
          {% else %}
          <form action="{% url 'app_one:follow' user_i_want_to_follow_id=userinfo.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Follow">
          </form>
          {% endifequal %}
      </div>
    </div>
  </div>
</div>
{% ifequal userinfo.user user %}
<div class="container">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">New Post.</h1>
      <form  method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="title_id">Title:</label>
          <input type="text" id="title_id" name="title" class="form-control" value="" placeholder="Title...">
        </div>
        <div class=" form-group">
          <label for="message_id">Message:</label>
          <textarea rows="4" cols="130" id="message_id" name="message" class="card-text form-control" placeholder="write here...."></textarea>
        </div>
        <input type="submit" class="btn btn-success" value="Post">
      </form>
    </div>
  </div>
</div>
{% endifequal %}
    <!-- <h1>{{userinfo.user.username}}</h1>
    <h1>{{userinfo.user.first_name}}</h1> -->
    <!-- <h1>{{userinfo.friends}}</h1> -->
   {% if userinfo.posts %}
      {% for post in userinfo.posts.all|dictsortreversed:"date_of_posting" %}
      <div class="container">
        <div class="card">
          <div class="card-header">
            <h3 class="Mytitle">{{post.title}}</h3>
            <h6>@{{post.posted_by.user.username}}, {{post.date_of_posting}}</h6>

          </div>

          <p class="Mymessage px-4">{{ post.message }}</p>
          <p class="px-2"><a href="{% url 'app_one:like' pk=post.id from='profile' %}">Likes</a>:{{post.likes.all|length}}  <a href="#">comments</a>:{{post.comments.all|length}}
          </p>

        </div>
        <form action="{% url 'app_one:comment' pk=post.id from='profile' %}" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-lg-10">
                <input type="text" name="comment" class="form-control" placeholder="Add a comment...">
            </div>
            <div class="col-lg-2">
              <input type="submit" class="btn btn-primary btn-block " value="Comment">
            </div>
          </div>

        </form>
        <div class="card">
        {% for comment in post.comments.all %}
            <h6 class="px-2">{{comment.commented_by}}, {{comment.date_of_commenting}}</h6>
            <p class="Mymessage px-4">{{comment.message}}</p>

        {% endfor %}
        </div>
      </div>

      <br><br>
      {% endfor %}
    {% else %}
      <h3>No post</h3>
    {% endif %}
    <script type="text/javascript">
      $('#edit_profile').click(function(){
        <!-- $('#my_alert').alert() -->
          <!-- $(".alert").alert('close') -->
        <!-- $('.my_alert').fadeout(5000) -->
      })
    </script>
  {% endblock %}

mychat/templates/app_one/signup.html
{% extends "app_one/base.html" %}
  {% block body_block %}
    <br>
  <div class="container card w-50">
    <div class="card-body">
      <h2 class="card-title text-center"> Sign Up</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

          <div class="form-group row fieldWrapper">
            {{ form.first_name.errors }}
            <label for="{{ form.first_name.id_for_label}}" class="col-sm-2">First Name:</label>
            <input type="text" name="{{ form.first_name.name}}" class="form-control col-sm-6" id="{{ form.first_name.id_for_label}}" value="" placeholder="First Name">
          </div>
          <div class="form-group row">
            {{ form.first_name.errors }}
            <label for="{{ form.last_name.id_for_label}}" class="col-sm-2">Last Name:</label>
            <input type="text" name="{{ form.last_name.name}}" class="form-control col-sm-6" value="" placeholder="Last Name">
          </div>

          <div class="form-group row">
            {{ form.username.errors }}
            <label for="{{ form.last_name.id_for_label}}" class="col-sm-2">Username:</label>
            <input type="text" name="{{ form.username.name}}"class="form-control col-sm-6" value="" placeholder="Username">
          </div>

          <div class="form-group row">
            {{ form.email.errors }}
            <label for="{{ form.email.id_for_label}}" class="col-sm-2">Email:</label>
            <input type="email" name="{{ form.email.name}}"class="form-control col-sm-6" value="" placeholder="example@gmail.com">
          </div>

          <div class="form-group row">
            {{ form.password.errors }}
            <label for="{{ form.password.id_for_label}}" class="col-sm-2">Password:</label>
            <input type="password" name="{{ form.password.name}}"class="form-control col-sm-6" value="" placeholder="password">
          </div>

          <input type="submit" name="" class="btn btn-primary" value="Create Account">


      </form>
    </div>

  </div>

  {% endblock %}